### ISSUE TITLE
get-pip.py is no longer compatible with python2.6

### ISSUE THREAD

**Issue by zhaoyongjie** [pyenv/pyenv-installer#70]
I have installed openssl, readline from homebrew, then use pyenv install python 2.6.7 cause error. 
I try to debug this error. I found pyenv may not be linked openssl.

```
yongjie.zhao@:workspace$ pyenv install 2.6.9
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.6.9.tgz...
-> https://www.python.org/ftp/python/2.6.9/Python-2.6.9.tgz
Installing Python-2.6.9...
patching file setup.py
Hunk #1 succeeded at 354 (offset 9 lines).
patching file ./configure
patching file ./Modules/readline.c
Hunk #1 succeeded at 199 (offset -7 lines).
Hunk #2 succeeded at 698 (offset -51 lines).
Hunk #3 succeeded at 808 (offset -51 lines).
Hunk #4 succeeded at 848 with fuzz 2 (offset -70 lines).
patching file ./setup.py
Hunk #1 succeeded at 1698 (offset 23 lines).
patching file ./Lib/ssl.py
patching file ./Modules/_ssl.c
python-build: use readline from homebrew
Installing pip from https://bootstrap.pypa.io/get-pip.py...
error: failed to install pip via get-pip.py

BUILD FAILED (OS X 10.13.3 using python-build 20160602)

Inspect or clean up the working tree at /var/folders/jh/43k6mlm116q4mzskbszmm2hh60hf8t/T/python-build.20180319143249.14627
Results logged to /var/folders/jh/43k6mlm116q4mzskbszmm2hh60hf8t/T/python-build.20180319143249.14627.log

Last 10 log lines:
		/Users/yongjie.zhao/.pyenv/versions/2.6.9/share/man/man1/python.1
Traceback (most recent call last):
  File "get-pip.py", line 22373, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "/var/folders/jh/43k6mlm116q4mzskbszmm2hh60hf8t/T/tmpnHxF2K/pip.zip/pip/__init__.py", line 34, in <module>
AttributeError: 'module' object has no attribute 'OPENSSL_VERSION_NUMBER'
```

**Comment by joshfriend** [comment]
[`OPENSSL_VERSION_NUMBER` was added in python 2.7](https://docs.python.org/2/library/ssl.html#ssl.OPENSSL_VERSION_NUMBER) so it appears that the default version of `get-pip.py` being served by bootstrap.pypa.io is no longer compatible with python 2.6.

@yyuu it looks like we have to add some logic to `build_package_get_pip` to determine if the user has python <2.6 or <3.2 and install from the appropriate version of `get-pip.py`

**Comment by yyuu** [comment]
If we need to keep maintain 2.6, we'd need to install some older version of setuptools/pip for these versions just like we did for 2.5, etc.

https://github.com/pyenv/pyenv/blob/v1.2.2/plugins/python-build/share/python-build/2.5.6#L4-L5

If I can believe the _classifiers_ of pip, 2.6 was still supported until 9.0.2.

https://github.com/pypa/pip/blob/9.0.2/setup.py#L58-L65

However, support for the version was dropped from the latest master branch. I'm guessing using 9.0.2 can be a workaround.

https://github.com/pypa/pip/blob/277bd6b00b9265d8578dc865b63626b7f5eafbad/setup.py#L50-L59

**Comment by zhaoyongjie** [comment]
@yyuu Thanks for you job,  can I fix this issue?

**Comment by yyuu** [comment]
In general, 2.6.x is way too old and it has already been EOL'd years ago. Even if you still need to deal with, do everything at your own risk/take care of yourself.

It looks like `get-pip.py` became noop starting from pip 8.0.1.

https://github.com/pypa/pip/blob/8.0.1/contrib/get-pip.py

It means that `PIP_VERSION` workaround won't work anymore for these versions.

https://github.com/pyenv/pyenv/blob/v1.2.2/plugins/python-build/bin/python-build#L2093-L2095

Plus, I found there's some issue looks similar to https://github.com/pypa/pip/issues/4528 with `get-pip.py` and `PIP_VERSION`. I guess we need somehow unset the environment variable to complete the pip's installation.

**Comment by yyuu** [comment]
At least I succeeded to manage installing some `pip` into 2.6.9. I've not yet verified the installed `pip` is actually working correctly or not, though.

```
FROM ubuntu:16.04
ENV DEBIAN_FRONTEND "noninteractive"
ENV PYENV_ROOT "/root/.pyenv"
ENV PATH "/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
RUN apt-get update && \
    apt-get -qy install git make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils
RUN git clone -b pip-version-workaround -q https://github.com/pyenv/pyenv /root/.pyenv
RUN PIP_VERSION=7.1.2 pyenv install -v 2.6.9
RUN pyenv global 2.6.9
RUN which python && python --version
```

// It looks like `get-pip.py` is always trying to install the latest release of `pip` on PyPI regardless of the version of `get-pip.py`.
// It might mean that there's no way to install `pip` on deprecated versions even with using the older version of `get-pip.py`.

**Comment by joshfriend** [comment]
As I noted on https://github.com/pypa/get-pip/issues/17#issuecomment-374314399, there _should_ be a `https://bootstrap.pypa.io/2.6/get-pip.py` url that will yield a 2.6 compatible `get-pip.py`. We should probably get the script from there instead of `pypa/pip`?

> In general, 2.6.x is way too old and it has already been EOL'd years ago. Even if you still need to deal with, do everything at your own risk/take care of yourself.

Agreed 100%, however, the current configuration for building 2.6.x fails at the ensurepip step causing the python to not be installed. If we skipped the ensurepip step, the user could take care of installing pip themselves, but as is, it is just broken completely.

That makes me think we should just remove EOL-ed pythons from pyenv. Python versions already have a very long lifetime before they become unsupported, I don't think it should be our job to keep them on life support for even longer.

**Comment by hugovk** [comment]
> That makes me think we should just remove EOL-ed pythons from pyenv. Python versions already have a very long lifetime before they become unsupported, I don't think it should be our job to keep them on life support for even longer.

Python 2.6 has been EOL since 2013-10-29, and is relatively little used (like the other EOLs, 3.0-3.3).

Here's the pip installs from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  73.85% |    362,071,915 |
| 3.6            |  12.92% |     63,337,814 |
| 3.5            |   8.17% |     40,075,882 |
| 3.4            |   4.19% |     20,540,641 |
| 2.6            |   0.71% |      3,480,030 |
| 3.3            |   0.08% |        406,934 |
| 3.7            |   0.07% |        360,437 |
| 3.2            |   0.00% |         23,511 |
| None           |   0.00% |         11,151 |
| 3.8            |   0.00% |          1,766 |

Source: `pypinfo --start-date -47 --end-date -20 --percent --pip --markdown "" pyversion`

**Comment by zhaoyongjie** [comment]
Python 2.6 is still installed by default in many Big Data distributions, such as Cloudera CHD 5.13(latest version).

**Comment by hugovk** [comment]
From what I can find it should be possible to to upgrade Cloudera CDH to Python 2.7, if not Python 3. Is that not feasible?

**Comment by joshfriend** [comment]
Closing in favor of https://github.com/pyenv/pyenv/issues/1127 since this issue is actually related to pyenv and not pyenv-installer
