### ISSUE TITLE
Install to /usr/local when using sudo.

### ISSUE THREAD

**Issue by tigerinus** [pyenv/pyenv-installer#79]
Latest version of python comes with Debian is 3.5. I need a newer version. I have daemon written in Python starting at boot time, which requires Python not be installed to any user folder.

Currently when using installer with sudo, Python is installed under /root. It'd be nice to recognize sudo privilege and install it to /usr/local instead.

Thanks!

**Comment by tigerinus** [comment]
You r right. I made my own change to pyenv installer and then realized pyenv is still looking under /root/.pyenv.
 
I don't know what should I be looking at in the link. As a debian user, I just want latest Python installed globally. The latest Python on Debian is still 3.5 but I have to work with some Python written in 3.7.

**Comment by obestwalter** [comment]
That link shows where the interpreters are located. You can change the `<pyenv root>` part of it (by setting `PYENV_ROOT`) so you could set that to wherever makes your daemon happy.

**Comment by tigerinus** [comment]
It's not my daemon. I could hack it to make it work obviously. But referring Python from a user directory for global use is just not a best practice to me.

**Comment by obestwalter** [comment]
> It's not my daemon.

I didn't mean that literally ... I don't even think it is legal to own daemons :laughing:.

> But referring Python from a user directory for global use is just not a best practice to me.

The original idea of pyenv was to give the user without sudo rights a chance to conveniently compile and install Python interpreters into their user directory and easily switch between them. So from the perspective of pyenv how I understand it, nstalling it with `sudo` is a bit of an exotic approach. If you have sudo rights there are other ways how to install interpreters into the "normal" directory according to the philosophy of the distro (usually meaning you compile the interpreter yourself and put it in the proper place). 

Having said that: it might be worth exploring that idea to let pyenv grow the functionality to do Python installations for you, when you have superuser rights, simply because it is more connvenient than doing it by hand. I am not using Debian directly anymore for a long time, so I had a look and it's apparently still a lot of manual steps to install a newer Python (as opposed to e.g. ubuntu, where you could use the deadsnakes ppa). 

IMO this is not really an installer topic though, but belongs over to pyenv. I would try to transer this issue over to pyenv if you don't mind (that github functionality is still beta though, so I don't know if it will work). If that doesn't work, you can open a new one referring to this discussion.

**Comment by tigerinus** [comment]
@obestwalter Thanks so much!

**Comment by obestwalter** [comment]
No problem, but no luck, I guess I would need to admin in pyenv, so please open a new issue there referencing this one: https://github.com/pyenv/pyenv

**Comment by obestwalter** [comment]
Closing as not an installer issue.

**Comment by sebma** [comment]
@obestwalter It seems git wants to clone inside an empty directory : 
```bash
$ curl -s https://pyenv.run | sudo PYENV_ROOT=/usr/local bash

WARNING: Can not proceed with installation. Kindly remove the '/usr/local' directory first.

```
So I did this instead : 
```bash
$ curl -s https://pyenv.run | sudo PYENV_ROOT=/usr/local/pyenv bash
Cloning into '/usr/local/pyenv'...
remote: Enumerating objects: 701, done.
remote: Counting objects: 100% (701/701), done.
remote: Compressing objects: 100% (530/530), done.
remote: Total 701 (delta 358), reused 263 (delta 79), pack-reused 0
Receiving objects: 100% (701/701), 390.80 KiB | 286.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
Cloning into '/usr/local/pyenv/plugins/pyenv-doctor'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 1), reused 2 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), 38.64 KiB | 465.00 KiB/s, done.
Resolving deltas: 100% (1/1), done.
Cloning into '/usr/local/pyenv/plugins/pyenv-installer'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 1), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (16/16), 6.01 KiB | 6.01 MiB/s, done.
Resolving deltas: 100% (1/1), done.
Cloning into '/usr/local/pyenv/plugins/pyenv-update'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (1/1), done.
Cloning into '/usr/local/pyenv/plugins/pyenv-virtualenv'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 57 (delta 11), reused 21 (delta 0), pack-reused 0
Receiving objects: 100% (57/57), 34.88 KiB | 420.00 KiB/s, done.
Resolving deltas: 100% (11/11), done.
Cloning into '/usr/local/pyenv/plugins/pyenv-which-ext'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 10 (delta 1), reused 6 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (1/1), done.

WARNING: seems you still have not added 'pyenv' to the load path.

# Load pyenv automatically by adding
# the following to ~/.bashrc:

export PATH="/usr/local/pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
Is this the right way to install pyenv systemwide ?
